#!/bin/bash

cp -r svg/* static/img
rm -rf public
cp -r static/apps/ public/
hugo --theme=cocoa
cd public
scp -o PubkeyAuthentication=no  -r * ofworlds@default.ofworldsandwoes.com:public_html/hyperparameter.space/
